name '42ways-railsapp'
version '1.0.0'
source 'https://github.com/42ways/puppet-railsapp.git'
author 'Thomas Herrmann, 42ways UG'
license 'Apache 2.0'
summary 'Basic Rails Server with MySQL, Apache, RVM and Passenger'
description 'Components for a basic passenger based rails server'
project_page 'https://github.com/42ways/puppet-railsapp'
dependency 'maestrodev/rvm', '>= 1.1.0'
dependency 'puppetlabs/apache', '>= 0.9.0'
dependency 'puppetlabs/firewall', '>= 0.4.0'
dependency 'puppetlabs/mysql', '>= 0.8.1'
